### ISSUE TITLE
Implement autocorrect

### ISSUE THREAD

**Issue by reibejoy** [TryGhost/Ghost-Desktop#149]
Please consider adding the autocorrect feature of an OS (OSX has a built in one). 
#145 is a somewhat related feature request.

**Comment by felixrieseberg** [comment]
I'm afraid that that is currently not possible - we're using the dictionary that is inside OS X, but we sadly can currently not directly implement the fully native OS X spellchecker.

If any open source warriors would like to try this in the future, the whole [Electron community](https://github.com/electron/electron) would be very thankful to you.

I'm closing this not because I wouldn't like to have it, but because I'm currently not aware of a way to implement the native spell checker.
