### ISSUE TITLE
Ghost Core upgrade notification confusing for desktop users

### ISSUE THREAD

**Issue by kevinSuttle** [TryGhost/Ghost-Desktop#167]
<img width="396" alt="screen shot 2016-07-08 at 11 35 51 am" src="https://cloud.githubusercontent.com/assets/95672/16692800/6bb8f6bc-4500-11e6-88e9-c10bab88655a.png"> = 👍 

Clicking takes me here: support.ghost.org/how-to-upgrade/ 👎

**Comment by ErisDS** [comment]
Hi there @kevinSuttle Could you explain why you're giving our support page a thumbs down? I'd love to improve it.

**Comment by kevinSuttle** [comment]
It's not the support page I'm giving 👎, it's the fact that clicking that link in the Ghost Desktop app (where the notification appears), takes me out to the browser, instead of "upgrading" my desktop app.

**Comment by felixrieseberg** [comment]
Oh, I see the confusion - it's not the desktop app that is out of date (that one should update itself without even bothering you), it's the blog itself that's in need of an update. And luckily for everyone, Hannah doesn't just mess with your blog ;-)

I'm closing in the meantime, but let me know if that was in error!

**Comment by kevinSuttle** [comment]
Yeah, it's pretty confusing (I know the difference, but still). 

<img width="1440" alt="screen shot 2016-07-08 at 3 20 33 pm" src="https://cloud.githubusercontent.com/assets/95672/16699050/9a2e66f2-451f-11e6-98f4-c5ec31b23f97.png">

**Comment by felixrieseberg** [comment]
We could potentially inject a little script that captures the string and changes it to something more specific (for desktop users only). Or, we could bake a quick if/else into core.

@ErisDS: Thoughts?

**Comment by ErisDS** [comment]
We're in the process of changing, upgrading, and replacing this system in Ghost.

We haven't used it in a while because it was confusing and not very useful. However, we have to get everyone to upgrade in order to get the new version of the feature!  Hence, this message would have popped up last week for anyone on <0.8.0 where they wouldn't have seen it since before 0.6.

If you want to do some sort of capture & replace in Ghost-Desktop to make the message clearer in that context that sounds like a great plan. Otherwise, once we get everyone onto 0.9 (coming soon) the messages will work differently.

**Comment by bnookala** [comment]
@ErisDS, @felixrieseberg I'll write up a lil' message rewrite here.
