### ISSUE TITLE
Pasting takes a full 3 Mississippi to apply

### ISSUE THREAD

**Issue by kevinSuttle** [TryGhost/Ghost-Desktop#168]
Copy something from your post in the editor. Attempt to paste via keyboard. 

_[1 Mississipi
2 Mississipi
3 Mississipi]_

Pasted item applies.

**Comment by bnookala** [comment]
It looks like a *lot* of time is being spent in the spellchecker when a large amount of text is pasted in. I've attached a profile from when I pasted 100 paragraphs of lorem ipsum into the spellchecker:

[spellchecker.cpuprofile.zip](https://github.com/TryGhost/Ghost-Desktop/files/360016/spellchecker.cpuprofile.zip)

I'll play around with it a bit more today, but If it does indeed turn out to be the spellchecker being slow (rather than our potential misuse of it), there's a second option we can try implementing: https://github.com/paulcbetts/electron-spellchecker
