### ISSUE TITLE
No data shown continuous spinner

### ISSUE THREAD

**Issue by balajikandasamy** [TryGhost/Ghost-Desktop#209]
I installed the latest version and tried adding my personal hosted blog. [prabhuspeaks.com](http://prabhuspeaks.com). The app doesn't show any content and keeps in endless loader icon. I didn't see any errors in the console and all HTTP request are served with data. I have an older version of ghost (0.7+) but would expect to have an error notification or backward support.
![error](https://cloud.githubusercontent.com/assets/8971237/19271168/5fc3f4ac-8f91-11e6-80a8-be64cc401f03.JPG)

**Comment by hashhar** [comment]
Same here.

**Comment by felixrieseberg** [comment]
Interesting - what seems to be happening is that we somehow managed to think that your admin lives at `http://prabhuspeaks.com/` rather than `http://prabhuspeaks.com/ghost`. You can probably start using the app right away if you enter the URL with the `ghost` appended, but we should figure out what's going on here.

In addition, we *should* just display the contents if loading succeeded.

**Comment by balajikandasamy** [comment]
That worked 👍 one minor issue always starts with a 404 page.
![image](https://cloud.githubusercontent.com/assets/8971237/19650417/4104b75e-99d7-11e6-9d3e-b3d6e6128766.png)

**Comment by balajikandasamy** [comment]
The issue is resolved. Now it no more required to provide /ghost it gets appended in the background. It was double time so I got 404
