### ISSUE TITLE
Czech spelling

### ISSUE THREAD

**Issue by tombarys** [TryGhost/Ghost-Desktop#290]
Could you add a Czech Spellchecker Dictionary option, please?
Thanks!

**Comment by ErisDS** [comment]
Hi @tombarys, unfortunately Ghost 1.0 is currently using the custom spellcheck built into SimpleMDE, which only supports US English at the present moment. We're aware this is not ideal, but the process of fixing this is not going to be quick. 

There's an issue here to track the need to hide the confusing dictionary setting in Ghost Desktop: https://github.com/TryGhost/Ghost-Desktop/issues/307

We're also working on [upgrading Ghost's editor](https://github.com/TryGhost/Ghost/issues/9311) so that it will support the browser/OS spellcheck again and you can also see two related upstream issues for SimplemDE [here](https://github.com/sparksuite/simplemde-markdown-editor/issues/658) and [here](https://github.com/sparksuite/simplemde-markdown-editor/issues/630).

At the present moment, there's no way for Ghost-Desktop to support spellcheck in other languages, unless one of these upstream issues is fixed. As this is not a problem with Ghost-Desktop (other than the setting, which is tracked in a different issue) I'm going to close this.

**Comment by tombarys** [comment]
Ok, thanks!

pá 8. 12. 2017 v 21:37 odesílatel Hannah Wolfe <notifications@github.com>
napsal:

**Comment by tombarys** [comment]
Hi, any improvement in this field? 

Option to switch-off the spellchecker at least would be welcome! :)

Best
Tomáš
