### ISSUE TITLE
Spellcheck in Linux 

### ISSUE THREAD

**Issue by artfors** [TryGhost/Ghost-Desktop#305]
The only language available is US English but I my self is and have Swedish as default language. On my Mac there is a choices for witch language I can use. And I know that I have Swedish dictionary installed.

**Comment by ErisDS** [comment]
Hi @artfors. I'm really sorry for the confusion here, unfortunately Ghost 1.0 is currently using the custom spellcheck built into SimpleMDE, which only supports US English at the present moment. We're aware this is not ideal, but the process of fixing this is not going to be quick. 

There's an issue here to track the need to hide the confusing dictionary setting in Ghost Desktop: https://github.com/TryGhost/Ghost-Desktop/issues/307

We're also working on [upgrading Ghost's editor](https://github.com/TryGhost/Ghost/issues/9311) so that it will support the browser/OS spellcheck again and you can also see two related upstream issues for SimplemDE [here](https://github.com/sparksuite/simplemde-markdown-editor/issues/658) and [here](https://github.com/sparksuite/simplemde-markdown-editor/issues/630).

At the present moment, there's no way for Ghost-Desktop to support spellcheck in other languages, unless one of these upstream issues is fixed. As this is not a problem with Ghost-Desktop (other than the setting, which is tracked in a different issue) I'm going to close this.
