### ISSUE TITLE
Spellcheck in Swedish on Windows 10

### ISSUE THREAD

**Issue by ollejacobsen** [TryGhost/Ghost-Desktop#306]
I'm a bit puzzled about the spell checking. In _Ghost: Electron_ i goto _preferences_ and select the dictionary I want to use. However it seems that the dictionary is faulty or that it's using the wrong dictionary. Since the most simple words are marked red.
What dictionary does the app use? Chrome or Windows 10?

![image](https://user-images.githubusercontent.com/687196/33758717-b753206a-dbff-11e7-998d-6911851d3c85.png)

Enable spell check for a post that's written in Swedish I get _errors_ on the most simple words. 
![image](https://user-images.githubusercontent.com/687196/33758758-f452b5fc-dbff-11e7-88e4-ba0722f39f50.png)

# Machine
- Windows 10 1703
- Running Ghost-Desktop: 1.5.0
- System language: English
- Region: Sweden

**Comment by ErisDS** [comment]
Hi @ollejacobsen, I'm really sorry for the confusion here, unfortunately Ghost 1.0 is currently using the custom spellcheck built into SimpleMDE, which only supports US English at the present moment. We're aware this is not ideal, but the process of fixing this is not going to be quick. 

There's an issue here to track the need to hide the confusing dictionary setting in Ghost Desktop: https://github.com/TryGhost/Ghost-Desktop/issues/307

We're also working on [upgrading Ghost's editor](https://github.com/TryGhost/Ghost/issues/9311) so that it will support the browser/OS spellcheck again and you can also see two related upstream issues for SimplemDE [here](https://github.com/sparksuite/simplemde-markdown-editor/issues/658) and [here](https://github.com/sparksuite/simplemde-markdown-editor/issues/630).

At the present moment, there's no way for Ghost-Desktop to support spellcheck in other languages, unless one of these upstream issues is fixed. As this is not a problem with Ghost-Desktop (other than the setting, which is tracked in a different issue) I'm going to close this.
