### ISSUE TITLE
Add "Find in Page" to the Ghost Instance

### ISSUE THREAD

**Issue by debrisslide** [TryGhost/Ghost-Desktop#80]
Not sure if this is an issue or an oversight, but Command+F is not available in ghost desktop to find text.
![screen shot 2016-03-28 at 1 34 17 pm](https://cloud.githubusercontent.com/assets/7127599/14084682/ed06cbac-f4e9-11e5-83f7-f4c7799ba7c9.png)

**Comment by bnookala** [comment]
Likely an oversight, but I think this could be filed as an enhancement. 

[Electron doesn't support find in page natively](https://github.com/atom/electron/issues/2037), but that doesn't us from making it work [via window.find](https://developer.mozilla.org/en-US/docs/Web/API/Window/find). We'd probably have to be a little smarter about it, since it would likely end up highlighting content outside of the ghost instance (sidebar, preferences pane, etc.).

Thoughts, @felixrieseberg?

**Comment by felixrieseberg** [comment]
Yeah, let's put it on the roadmap. Good news though: While the UI isn't there, the methods (findInPage and stopFindInPage) are: https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentsfindinpagetext-options
